package:
  name: msmbuilder2022
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    #- pip
    - python 
    - mdtraj
    - cython
    - numpy >=1.17, <= 1.23
    - libgomp  # [linux]
    - setuptools
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - mdtraj
    - numpy >=1.17, <= 1.23
    - scikit-learn >0.21.1
    - pandas
    - fastcluster
    - jinja2 <3.1
    - pyyaml
    - pyhmc
    - pytables
    - numpydoc
    - six
    - scipy
    - libgomp  # [linux]

test:
  imports:
    - msmbuilder
    - msmbuilder.cluster
    - msmbuilder.commands
    - msmbuilder.decomposition
    - msmbuilder.example_datasets
    - msmbuilder.feature_extraction
    - msmbuilder.feature_selection
    - msmbuilder.featurizer
    - msmbuilder.hmm
    - msmbuilder.io
    - msmbuilder.libdistance
    - msmbuilder.lumping
    - msmbuilder.msm
    - msmbuilder.preprocessing
    - msmbuilder.scripts
    - msmbuilder.tests
    - msmbuilder.tpt
    - msmbuilder.utils
  commands:
    - msmb -h

about:
  home: https://github.com/msmbuilder/msmbuilder2022
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
