package:
  name: msmbuilder2022
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # number: 0
  entry_points:
    - msmb = msmbuilder.scripts.msmb:main


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    #- pip
    - python 
    - mdtraj
    - cython
    - numpy >=1.17
    - libgomp  # [linux]
    - setuptools
    #- scikit-learn >0.21.1
    #- numpydoc
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - mdtraj
    - scikit-learn >0.21.1
    - pandas
    - fastcluster
    - jinja2 <3.1
    - pyyaml
    - pyhmc
    - pytables
    - numpydoc
    - six
    - scipy
    - libgomp  # [linux]

test:
  requires:
    - pytest
    - munkres
    - numdifftools
    - statsmodels
    - hmmlearn
    - cvxpy # [not win]
    - msmb_data

  imports:
    - msmbuilder
    - msmbuilder.cluster
    - msmbuilder.commands
    - msmbuilder.decomposition
    - msmbuilder.example_datasets
    - msmbuilder.feature_extraction
    - msmbuilder.feature_selection
    - msmbuilder.featurizer
    - msmbuilder.hmm
    - msmbuilder.io
    - msmbuilder.libdistance
    - msmbuilder.lumping
    - msmbuilder.msm
    - msmbuilder.preprocessing
    - msmbuilder.scripts
    - msmbuilder.tests
    - msmbuilder.tpt
    - msmbuilder.utils
  #source_files:
    # - ../../
    #- run_test.sh
    # - ../../msmbuilder/tests/

  commands:
    - conda list
    #- pip show msmbuilder
    - pip show msmbuilder2022
    - msmb -h
    #- pytest -v 

#test:
  #requires:
    #- nose
    #- nose-timer
    #- munkres
    #- numdifftools
    #- statsmodels
    #- hmmlearn
    #- cvxpy # [not win]
    #- msmb_data
  #imports:
    #- msmbuilder
  #commands:
    #- msmb -h
    #- nosetests msmbuilder -v --with-timer --timer-ok 2 --timer-warning 10 --timer-filter error


about:
  home: https://github.com/msmbuilder/msmbuilder
  license: LGPLv2.1+
  summary: 'MSMBuilder: Statistical models for biomolecular dynamics'
