name: Build msmbuilder2022 source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7","3.8","3.9"]

    steps:
    - uses: actions/checkout@v3
    #- name: Set up Python ${{ matrix.python-version }}
      #uses: actions/setup-python@v4
      #with:
        #python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        conda activate test
        conda list
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $GITHUB_PATH
        echo $CONDA/bin
        echo $CONDA/bin >> $GITHUB_PATH
        echo $GITHUB_PATH
        echo $CONDA/bin
        # conda config --add channels conda-forge 
        # conda config --add channels omnia 
    - name: Install required packages 
      run: |
        #conda install -yq conda-build jinja2 conda-verify
        #python -m pip install --upgrade pip
        #conda update conda-build
        conda list
    - name: Conda build    
      run: |
        conda list
        conda build --quiet devtools/conda-recipe 
    - name: Test with pytest
      run: |
        conda install -yq --use-local msmbuilder2022
        conda install -yq pytest numdifftools hmmlearn nose
        mkdir ../../pkgs
        cp -r msmbuilder/tests ../../pkgs
        cd ../../pkgs
        python tests/data_init.py
        pytest tests/ -v
        
