name: Build msmbuilder2022 source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7","3.8","3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels conda-forge 
        conda config --add channels omnia 
    - name: Install required packages 
      run: |
        # conda install -yq conda-build jinja2 conda-verify
        conda install -yq conda-build conda-verify 
    # - name: Install dependencies
      # run: |
        # conda env update --file environment.yml --name base
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests
    - name: Conda build    
      run: |
        mkdir output_build
        # conda install conda-build
        # conda update conda
        conda update conda-build
        # conda build --croot ./output_build
        conda build --quiet devtools/conda-recipe
    #- name: Lint with flake8
      #run: |
        #conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        ls 
        conda list
        # environ.get('GIT_DESCRIBE_TAG')
        echo $GIT_DESCRIBE_TAG
        # conda install pytest munkres numdifftools statsmodels hmmlearn cvxpy scikit-learn numpydoc
        # conda install -c omnia msmb_data
        # python -m pytest msmbuilder -W ignore::DeprecationWarning
        # pytests