name: Build msmbuilder2022 source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7","3.8","3.9"]
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        # activate-environment: test
    - name: Install required packages 
      run: |
        conda config --add channels conda-forge 
        conda install -yq conda-build jinja2 conda-verify
        python -m pip install --upgrade pip
        conda update conda-build
    - name: Conda build 
      run: |
        conda build --quiet devtools/conda-recipe 
    - name: Test with pytest
      run: |
        conda install -yq -c ${CONDA_PREFIX}/conda-bld/ msmbuilder2022
        conda install -yq pytest numdifftools hmmlearn nose
        mkdir ../../pkgs
        cp -r msmbuilder/tests ../../pkgs
        cd ../../pkgs
        python tests/data_init.py
        pytest tests/ -v
        
